name: Update data

on:
  schedule:
    - cron:  '0 * * * *' # runs every hour
  workflow_dispatch:

jobs:
  update_data:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - uses: actions/checkout@v2
    - uses: metaodi/equalstreetnames-todo/.github/workflows/update_city_data.yml@main
      with:
        city: zurich
