name: Update city data

on:
  workflow_call:
     city:
        description: 'City'
        required: true
        default: 'zurich' 
        type: choice
        options:
        - zurich
        - winterthur

jobs:
  update_city_data:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Prepare data
      run: python fetch_data.py -c ${{ inputs.city }}
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.city }}
        path: data.pkl
