name: Update data

on:
  schedule:
    - cron:  '0 * * * *' # runs every hour
  workflow_dispatch:

jobs:
  update_zurich_data:
    uses: ./.github/workflows/update_city_data.yml
    with:
      city: zurich
      
  update_winterthur_data:
    uses: ./.github/workflows/update_city_data.yml
    with:
      city: winterthur
    
